### ISSUE TITLE
Add Edit Password Feature In The Account Page

### ISSUE THREAD

**Issue by konstantians** [konstantians/SocialMediaApp#16]
Give the option to the user to change their password in their account page.

**Comment by krishnasvp** [comment]
Hey, @konstantians could you please guide me on which file exactly am I supposed to make the changes on. 
![image](https://github.com/konstantians/SocialMediaApp/assets/133650795/122ef3b6-2ca6-48f5-8fe1-b554a07adcfe)

**Comment by konstantians** [comment]
Hey, @krishnasvp this is an assignment that I have for my university and somehow it has attracted a lot of attention, if you want to help this could be cool(this has never happened to me before lol). 
The steps are the following:
1. You have to add an action/method in the account controller that takes care of the change of the password(use the ```ChangePasswordAsync``` from the ```_authenticationProcedures``` field - this is dependency injection btw).
2. Add a modal(whatever you want, but I would suggest a bootstrap modal, because it is easier) when the user clicks on the button next to the password field in the EditAccount page.
3. Add some alerts like I have done with ```ViewData["x"]``` for possible backend errors if you can think of something and there is no need for frontend validation since the validation attributes as you can see take care of that.

That should be all.
To get to the EditAccount Page you need to first log in, which requires email confirmation so either add a real account you have or message me back, so that I can create some dummy accounts. I think I will write some documentation in the README.md, so that if anyone wants to help they will have a better understanding of what is going on(give me a second on that).
